version: '2'

services:
  app:
    build: .
    volumes:
      - ".:/var/myapp"
    environment:
      - "TZ=Asia/Tokyo"
      - "S3_ENDPOINT=${S3_ENDPOINT}"
      - "S3_REGION=${S3_REGION}"
      - "S3_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${S3_SECRET_KEY}"
      - "S3_BUCKET=${S3_BUCKET}"
      - "S3_FOLDER=${S3_FOLDER}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "API_CRAWL_AND_VOTE_URL=${API_CRAWL_AND_VOTE_URL}"
      - "API_CRAWL_AND_CLOSE_URL=${API_CRAWL_AND_CLOSE_URL}"
      - "API_RUNDECK_AUTH_TOKEN=${API_RUNDECK_AUTH_TOKEN}"
    ports:
      - "5000:5000"
    depends_on:
      - "s3"
      - "db"

  s3:
    image: minio/minio
    environment:
      - "MINIO_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${S3_SECRET_KEY}"
      - "MINIO=REGION=${S3_REGION}"
    command: server /data

  db:
    image: postgres:12
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_DATABASE}"
