version: '3'

services:
  app:
    build: .
    environment:
      - "AWS_S3_ACCESS_KEY=s3_access_key"
      - "AWS_S3_SECRET_KEY=s3_secret_key"
      - "AWS_S3_REGION=my_region"
      - "AWS_S3_BUCKET=test.scoring-horse-racing"
      - "AWS_S3_ENDPOINT=http://s3:9000"
      - "AWS_S3_FORCE_PATH_STYLE=true"
    volumes:
      - ".:/var/myapp"
    depends_on:
      - "s3"
    command: /bin/sh -c "bundle install && rake spec"
  s3:
    image: minio/minio
    environment:
      - "MINIO_ACCESS_KEY=s3_access_key"
      - "MINIO_SECRET_KEY=s3_secret_key"
      - "MINIO_REGION=my_region"
    volumes:
      - "s3:/export"
    command: server /export

volumes:
  s3:
    driver: local
