version: '3'

services:
  app:
    build: .
    environment:
      - "AWS_S3_ACCESS_KEY=s3_access_key"
      - "AWS_S3_SECRET_KEY=s3_secret_key"
      - "AWS_S3_REGION=my_region"
      - "AWS_S3_BUCKET=test.horse-racing"
      - "AWS_S3_ENDPOINT=http://s3:9000"
      - "AWS_S3_FORCE_PATH_STYLE=true"
      - "DB_DATABASE=db"
      - "DB_USERNAME=db_user"
      - "DB_PASSWORD=db_pass"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "CRAWLINE_LOGGER_LEVEL=FATAL"
      - "APP_LOGGER_LEVEL=FATAL"
    volumes:
      - ".:/var/myapp"
    depends_on:
      - "s3"
      - "db"
    command: /bin/sh -c "bundle install && rake db:migrate && rake spec && rake build"
  s3:
    image: minio/minio
    environment:
      - "MINIO_ACCESS_KEY=s3_access_key"
      - "MINIO_SECRET_KEY=s3_secret_key"
      - "MINIO_REGION=my_region"
    volumes:
      - "s3:/export"
    command: server /export
  db:
    image: postgres:11
    environment:
      - "POSTGRES_USER=db_user"
      - "POSTGRES_PASSWORD=db_pass"
      - "POSTGRES_DB=db"
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  s3:
    driver: local
  db:
    driver: local
